@startuml
class View {

  +criar_admin()

  +bibliotecario_autenticar(cpf, senha)
  +bibliotecario_listar()
  +bibliotecario_inserir(cpf, senha)
  +bibliotecario_atualizar(cpf, senha)
  +bibliotecario_excluir(cpf)

  +usuario_autenticar(cpf, senha)
  +usuario_listar()
  +usuario_listar_cpf(cpf)
  +usuario_inserir(cpf, matricula, nome, email, telefone, senha)
  +usuario_atualizar(cpf, matricula, nome, email, telefone, senha)
  +usuario_excluir(cpf)

  +autor_listar()
  +autor_listar_id(id)
  +autor_inserir(nome)
  +autor_atualizar(id, nome)
  +autor_excluir(id)

  +livro_listar()
  +livro_listar_codigo(codigo)
  +livro_inserir(codigo, nome)
  +livro_atualizar(codigo, nome)
  +livro_excluir(codigo)

  +autoria_listar()
  +autoria_inserir(id_autor, codigo_livro)
  +autoria_excluir(id_autor, codigo_livro)

  +exemplar_listar()
  +exemplar_listar_id(id)
  +exemplar_inserir(codigo_livro)
  +exemplar_atualizar(id, disponibilidade, codigo_livro)
  +exemplar_excluir(id)

  +emprestimo_listar()
  +emprestimo_inserir(dt_emprestimo, dt_prazo, cpf_usuario, id_exemplar)
  +emprestimo_devolver(id, dt_devolucao)

  +multa_listar()
  +multa_inserir(id_emprestimo, valor, descricao)
  +multa_excluir(id)
}
@enduml
